name: Continuous Integration
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Cmake
        run: cmake -B ${{github.workspace}}/build
      - name: Build Cmake
        run: cmake --build ${{github.workspace}}/build --target VDSProject_test -j4
      - name: Test
        run: ${{github.workspace}}/build/src/test/VDSProject_test
